---
pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'

  - script: |
      cd ../
      mv $(Build.SourcesDirectory) sample-role-for-ci-testing
      cd sample-role-for-ci-testing
      python -m pip install --upgrade pip setuptools wheel
      pip install pipenv
      pipenv sync --dev

  - script: |
      pipenv run check
      pipenv run test
