---
version: 2

anchors:
  DEFAULTS: &DEFAULTS
    machine: true
    environment:
      PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/sample-playbook-for-ci-testing

  RESTORE_CACHE: &RESTORE_CACHE
    restore_cache:
      key: 'sample-role-v1-{{ checksum "Pipfile.lock" }}'

  INSTALL_ANSIBLE_RELATED_PACKAGES: &INSTALL_ANSIBLE_RELATED_PACKAGES
    run:
      command: |
        pip --version
        pip install pipenv
        pipenv sync

jobs:
  build:
    <<: *DEFAULTS
    steps:
      - checkout
      - *RESTORE_CACHE

      - *INSTALL_ANSIBLE_RELATED_PACKAGES

      - save_cache:
          key: 'sample-role-v1-{{ checksum "Pipfile.lock" }}'
          paths:
            - .venv

      - run:
          command: pipenv run test
