---
version: 2
jobs:
  build:
    machine: yes
    working_directory: ~/sample-role-for-ci-testing
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      - restore_cache:
          key: sample-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          command: |
            pip install pipenv
            pipenv sync

      - save_cache:
          key: sample-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"

      - run:
          command: pipenv run test
