---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  config_options:
    diff:
      always: true
  lint:
    name: ansible-lint
    options:
      L: true
      force-color: true
scenario:
  name: default
  check_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - check
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
